package com.springboot.bankbackend.utils;

public enum TransactionCategory {
    GROCERY, ESSENTIALS, ENTERTAINMENT, EATING_OUT, PERSONAL,
    TRANSPORTATION, SUBSCRIPTION, FIXED_EXPENSE, ONETIME_EXPENSE, RENT, OTHER, UNCATEGORIZED
}
