package com.springboot.bankbackend.utils;

public enum TransactionCategory {
    FOOD_GROCERY, OTHER_GROCERY, RESTAURANT, ENTERTAINMENT, EATING_OUT, PERSONAL,
    TRANSPORTATION, SUBSCRIPTION, FIXED_EXPENSE, ONETIME_EXPENSE, RENT, OTHER
}
